version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=debug
